#!/bin/bash

password=${1:-p@ssw0rd}

for user in student{1..10} instructor; do
  echo "${user}:${password}" | chpasswd
  docker run --detach --name=chinook-mysql-${user} quintessence/chinook-mysql
  sleep 2
  docker run --detach --name=mysql-${user} --env="MYSQL_ROOT_PASSWORD=p@ssw0rd" mysql:latest
  sleep 2
  docker run --detach --name=postgres-${user} -d postgres:latest
  sleep 2
done
